name: ascent
description: A database for rock climbing ascents
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.0+1
environment:
  sdk: ^3.4.1
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.3
  flutter_search_bar:
    git:
      url: https://github.com/JulienDev/flutter-search-bar
      ref: master
dev_dependencies:
  test: ^1.25.2
flutter:
  uses-material-design: true
