name: ascent
description: A database for rock climbing ascents
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.2.0
environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  file_picker: ^10.1.9
  flutter_search_bar:
    git:
      url: https://github.com/JulienDev/flutter-search-bar
      ref: master
dev_dependencies:
  test: ^1.26.2
flutter:
  uses-material-design: true
